import type { Metadata } from "next";
import { DM_Sans, Prompt } from "next/font/google";
import "./globals.css";
import MainLayout from "@/components/layout/MainLayout";
import { Toaster, toast } from "sonner";
const geistMono = DM_Sans({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: ["400"],
});
const promt = Prompt({
  variable: "--font-prompt",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistMono.className} ${promt.variable}`}>
        <Toaster richColors position="top-center" />
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
